ci: generate hugo_stats.json if missing

diff --git a/.github/workflows/cloudflare-pages.yaml b/.github/workflows/cloudflare-pages.yaml
--- a/.github/workflows/cloudflare-pages.yaml
+++ b/.github/workflows/cloudflare-pages.yaml
@@ -29,7 +29,7 @@ jobs:
     permissions:
       contents: read
     env:
-      HUGO_VERSION: 0.121.1
+      HUGO_VERSION: 0.121.2
       # Define the branch name variable
       BRANCH_NAME: ${{ github.ref_name }}
 
@@ -63,7 +63,22 @@ jobs:
           key: ${{ runner.os }}-hugo-resources-${{ env.BRANCH_NAME }}-${{ github.run_id }}
           restore-keys: |
             ${{ runner.os }}-hugo-resources-${{ env.BRANCH_NAME }}-
-            ${{ runner.os }}-hugo-resources-main- # Fallback to main branch cache
+
+      - name: Check for hugo_stats.json
+        env:
+          # For maximum backward compatibility with Hugo modules
+          HUGO_ENVIRONMENT: production
+          HUGO_ENV: production
+          HUGO_CLARIS_AUTHOR_EMAIL: ${{ secrets.HUGO_CLARIS_AUTHOR_EMAIL }}
+        run: |
+          if ! [ -f hugo_stats.json ]; then
+            echo "Running hugo to create 'hugo_stats.json' as this required file is missing."
+            hugo --gc --minify
+          fi
+          if ! [ -f hugo_stats.json ]; then
+            echo "Fatal error: Hugo failed to create hugo_stats.json"
+            exit 1
+          fi
 
       - name: Build with Hugo
         env:
